carla:
  host: "localhost"
  port: 2000

experiment:
  controlled_count: 2
  free_count: 10
  spawn_max_attempts: 10
  sensor_type: "lidar"
  lidar:
    x: 0.0
    y: 0.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

debug:
  delta_seconds: 0.1