carla:
  host: "localhost"
  port: 2000

other:
  pedestrian_count: 0

experiment:
  policy: "local"

  road_point_extractor:
    step_size : 0.5
    search_radius: 50
    search_n_points: 200

  controlled_count: 2
  route_planning_enable: True
  sensorless_free_agent: True #False for CMPE assignment data collections
  free_count: 10
  spawn_max_attempts: 100
  sensor_type: "lidar"
  lidar:
    x: 0.0
    y: 0.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

debug:
  delta_seconds: 0.1