carla:
  host: "localhost"
  port: 2000

other:
  pedestrian_count: 0

experiment:
  controlled_count: 0
  sensorless_free_agent: True
  free_count: 20
  spawn_max_attempts: 100
  sensor_type: "lidar"
  lidar:
    x: 0.0
    y: 0.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

debug:
  delta_seconds: 0.1